default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: <%= ENV['DATABASE_PASSWORD'] %>
  port: 3306
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: rails_practice_development

test:
  <<: *default
  database: rails_practice_test

production:
  <<: *default
  database: rails_practice_production
  username: rails_practice
  password: <%= ENV["RAILS_PRACTICE_DATABASE_PASSWORD"] %>
